### ISSUE TITLE
Cannot build the project with Maven

### ISSUE THREAD

**Issue by vkorenev** [cloudstateio/kotlin-support#11]
I checked out the project and tried to build it with `mvn clean package`. That failed:
```
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ cloudstate-kotlin-support ---
[INFO] Surefire report directory: /home/vkorenev/Projects/Cloudstate/kotlin-support/cloudstate-kotlin-support/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NoClassDefFoundError: com/example/shoppingcart/persistence/Domain$Cart
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.apache.maven.surefire.util.ReflectionUtils.tryGetMethod(ReflectionUtils.java:57)
	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isSuiteOnly(JUnit3TestChecker.java:64)
	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isValidJUnit3Test(JUnit3TestChecker.java:59)
	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.accept(JUnit3TestChecker.java:54)
	at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.accept(JUnit4TestChecker.java:51)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:97)
	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.example.shoppingcart.persistence.Domain$Cart
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 22 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for kotlin-support 0.4.3:
[INFO] 
[INFO] cloudstate-kotlin-support .......................... FAILURE [ 10.427 s]
[INFO] shopping-cart ...................................... SKIPPED
[INFO] kotlin-pingpong .................................... SKIPPED
[INFO] kotlin-chat ........................................ SKIPPED
[INFO] kotlin-support ..................................... SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.798 s
[INFO] Finished at: 2020-04-18T13:49:20-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project cloudstate-kotlin-support: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```
Just trying to compile everything also fails:
```
[INFO] --- maven-compiler-plugin:3.5.1:compile (java-compile) @ shopping-cart ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/target/classes
[INFO] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java: Some input files use or override a deprecated API.
[INFO] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3738,24] cannot find symbol
  symbol:   class EventsProto
  location: package io.cloudstate
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3741,25] cannot find symbol
  symbol:   class HttpBodyProto
  location: package com.google.api
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3776,31] cannot find symbol
  symbol:   class EventsProto
  location: package io.cloudstate
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3782,18] cannot find symbol
  symbol:   class EventsProto
  location: package io.cloudstate
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3785,19] cannot find symbol
  symbol:   class HttpBodyProto
  location: package com.google.api
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for kotlin-support 0.4.3:
[INFO] 
[INFO] cloudstate-kotlin-support .......................... SUCCESS [ 10.071 s]
[INFO] shopping-cart ...................................... FAILURE [  1.455 s]
[INFO] kotlin-pingpong .................................... SKIPPED
[INFO] kotlin-chat ........................................ SKIPPED
[INFO] kotlin-support ..................................... SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.867 s
[INFO] Finished at: 2020-04-18T13:53:25-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (java-compile) on project shopping-cart: Compilation failure: Compilation failure: 
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3738,24] cannot find symbol
[ERROR]   symbol:   class EventsProto
[ERROR]   location: package io.cloudstate
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3741,25] cannot find symbol
[ERROR]   symbol:   class HttpBodyProto
[ERROR]   location: package com.google.api
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3776,31] cannot find symbol
[ERROR]   symbol:   class EventsProto
[ERROR]   location: package io.cloudstate
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3782,18] cannot find symbol
[ERROR]   symbol:   class EventsProto
[ERROR]   location: package io.cloudstate
[ERROR] /home/vkorenev/Projects/Cloudstate/kotlin-support/examples/shopping-cart/src/main/kotlin/com/example/shoppingcart/Shoppingcart.java:[3785,19] cannot find symbol
[ERROR]   symbol:   class HttpBodyProto
[ERROR]   location: package com.google.api
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :shopping-cart
```
My `mvn --version` output:
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: AdoptOpenJDK, runtime: /home/vkorenev/.sdkman/candidates/java/8.0.242.hs-adpt/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-24-generic", arch: "amd64", family: "unix"
```

**Comment by sleipnir** [comment]
Hello @vkorenev , thank you very much for trying kotlin-support.
Unfortunately it is necessary to generate the binaries of the protobuf classes in the sample projects before trying to compile the entire project. This is something that I have not yet resolved to perform all the steps at once in the build process. I'll take a look at your PR and send you the feedbacks.
